from lib import *

# (titre, objectif, prompt, adapter, exemple)
P = [
("IDÉES DE PUBLICATIONS", [
("30 idées de publications",
 "Ne plus jamais manquer d'idées pour ta page ou celle d'un client.",
 "Agis comme un community manager expérimenté en Afrique francophone.\nContexte : je gère la page <b>[type d'activité]</b> à <b>[ville]</b>. Cible : <b>[cible]</b>.\nObjectif : proposer 30 idées de publications pour 1 mois.\nContraintes : mélange de 40 % éducatif, 30 % preuve/témoignage, 30 % vente. Pas de sujets qui nécessitent un gros budget.\nFormat : tableau avec colonnes Jour / Idée / Type / Support (photo, vidéo, texte).",
 "Change l'activité, la ville et la répartition éducatif/vente selon ton client.",
 "Jour 1 · « 3 erreurs en choisissant un tissu wax » · Éducatif · Carrousel photo\nJour 2 · Photo avant/après d'une commande livrée · Preuve · Photo"),
("Idées à partir d'une question client",
 "Transformer les questions reçues en contenu utile.",
 "Voici 5 questions que mes clients posent souvent par WhatsApp : <b>[liste]</b>.\nPour chaque question, propose : 1) un titre de publication, 2) une idée de contenu en 3 points, 3) un appel à l'action doux.\nTon : simple, rassurant, local.",
 "Colle de vraies questions reçues (sans nom ni numéro de client).",
 "Question : « Vous livrez à Bonabéri ? »\nTitre : « Livraison à Douala : zones, délais, tarifs »\nPoints : zones couvertes / délai habituel / comment commander"),
]),
("POSTS FACEBOOK", [
("Post Facebook de présentation",
 "Présenter une activité de façon claire et humaine.",
 "Écris un post Facebook de 100 mots maximum pour présenter <b>[activité]</b> à <b>[ville]</b>.\nCible : <b>[cible]</b>. Ton : chaleureux et professionnel.\nÉléments à inclure : <b>[3 avantages réels]</b>.\nTermine par une question simple pour encourager les commentaires, puis l'appel à écrire sur WhatsApp au <b>[numéro]</b>.\nÉvite les exagérations et les promesses garanties.",
 "Ajoute ton histoire personnelle pour rendre le post unique.",
 "« Bonjour à tous 👋 Je suis Aïcha, couturière à Douala. Je crée des tenues en wax sur mesure, livrées en 7 jours… Quelle tenue aimeriez-vous voir en ce moment ? »"),
("Post de promotion honnête",
 "Annoncer une offre sans mentir.",
 "Rédige un post Facebook pour annoncer <b>[offre]</b> valable jusqu'au <b>[date]</b>.\nPrix : <b>[prix] FCFA</b>. Public : <b>[cible]</b>.\nStructure : accroche, bénéfice concret, détails pratiques (quantité, livraison), appel à l'action.\nInterdit : fausse urgence, chiffres inventés.",
 "Précise toujours les conditions réelles (stock, zone de livraison).",
 "« Offre de la semaine : pack de 20 fiches produits à 10 000 FCFA au lieu de 15 000, jusqu'à dimanche… »"),
("Post de preuve sociale",
 "Valoriser un résultat réel de client.",
 "À partir de ces informations réelles : <b>[résultat/témoignage autorisé]</b>, rédige un post Facebook de 90 mots qui raconte la situation de départ, ce que j'ai fait, et le retour du client.\nTon : sobre, sans exagération. Ne rajoute aucun chiffre qui ne figure pas dans mes informations.",
 "Demande l'accord du client avant de publier son retour.",
 "« Fatou vendait ses sacs uniquement par bouche-à-oreille. Nous avons clarifié ses descriptions et organisé un catalogue photo. Son retour : “C'est plus facile pour mes clientes de choisir.” »"),
]),
("SCRIPTS TIKTOK ET HOOKS", [
("Script TikTok de 30 secondes",
 "Créer une vidéo courte structurée.",
 "Écris un script TikTok de 30 secondes sur : <b>[sujet]</b>.\nCible : <b>[cible]</b>. Langage oral simple, phrases courtes.\nStructure : Accroche (3 s) / Problème (7 s) / Solution en 3 étapes (15 s) / Appel à l'action (5 s).\nDonne aussi : texte à l'écran, idée de plan de caméra avec un simple smartphone, 5 hashtags.",
 "Ajuste le temps (15 s, 45 s) et le niveau de langage selon ton style.",
 "Accroche : « Tu perds des clients sur WhatsApp à cause de ça… »\nÉtape 1 : réponds en moins de 10 minutes…"),
("Script de storytime",
 "Raconter une expérience pour créer de la connexion.",
 "Transforme cette expérience vécue en script TikTok de 45 secondes : <b>[ton histoire]</b>.\nFormat : début accrocheur, tension, leçon pratique en une phrase.\nStyle : parlé, naturel, un peu d'humour, sans exagérer les faits.",
 "Garde les faits vrais : tu peux simplifier, pas inventer.",
 "« Mon premier client m'a écrit à 22 h pour dire que mon texte était “trop compliqué”. Voilà ce que j'ai changé… »"),
("20 hooks (accroches)",
 "Obtenir des débuts de vidéos qui retiennent l'attention.",
 "Propose 20 accroches pour des vidéos courtes sur <b>[sujet]</b>, destinées à <b>[cible]</b>.\nMélange : question, erreur courante, chiffre vérifiable, contraste avant/après, mini-secret honnête.\nChaque accroche : 12 mots maximum. Pas de clickbait mensonger.",
 "Garde les 3 meilleures et teste-les sur 3 vidéos différentes.",
 "« Ton message WhatsApp fait fuir les clients ? »\n« 3 phrases à ne plus écrire à un prospect. »"),
]),
("CAPTIONS, STORYTELLING", [
("Légende Instagram",
 "Écrire des légendes lisibles et engageantes.",
 "Écris 3 versions d'une légende Instagram pour cette photo : <b>[description de l'image]</b>.\nActivité : <b>[activité]</b>. Ton : <b>[ton]</b>.\nVersion 1 : courte (20 mots). Version 2 : conseil utile. Version 3 : mini-histoire.\nAjoute 8 hashtags pertinents et un appel à l'action.",
 "Mélange hashtags larges et locaux (ville, pays).",
 "V1 : « Nouvelle collection, même passion. Disponible dès demain. »"),
("Storytelling de marque",
 "Raconter pourquoi tu fais ce que tu fais.",
 "Aide-moi à écrire mon histoire de marque en 150 mots.\nInformations : mon parcours <b>[parcours]</b>, ce qui m'a motivé <b>[raison]</b>, le problème que je résous <b>[problème]</b>.\nStyle : sincère, direct, sans grandes phrases vides. Termine par ce que je propose aujourd'hui.",
 "Pose-toi la question : qu'est-ce qui me rend crédible ici ?",
 "« J'ai commencé à aider des vendeurs de mon quartier à rédiger leurs annonces après avoir remarqué que de bons produits se vendaient mal… »"),
("Histoire client (cas réel)",
 "Mettre en valeur un avant/après.",
 "Raconte en 120 mots l'histoire de ce client : <b>[situation de départ]</b> → <b>[ce que j'ai fait]</b> → <b>[résultat observé]</b>.\nConserve les faits exacts, anonymise si nécessaire.\nFormat : 3 courts paragraphes + une phrase de conclusion.",
 "Remplace le nom par un prénom d'emprunt si le client le préfère.",
 "« Avant : peu de réponses aux annonces. Pendant : textes plus clairs. Après : plus de questions précises en messages privés. »"),
]),
("CALENDRIER ÉDITORIAL", [
("Calendrier de 4 semaines",
 "Planifier sans stress.",
 "Crée un calendrier éditorial de 4 semaines pour <b>[activité]</b> sur Facebook et TikTok.\nFréquence : <b>[3 publications par semaine]</b>. Cible : <b>[cible]</b>.\nObjectif principal : <b>[objectif]</b>.\nFormat : tableau Semaine / Jour / Plateforme / Sujet / Format / Appel à l'action.\nChaque semaine a un thème différent.",
 "Réduis la fréquence si tu es seul(e) : régularité avant volume.",
 "S1 · Mardi · Facebook · Présentation de l'activité · Photo + texte · Écrire sur WhatsApp"),
("Calendrier autour d'un événement",
 "Préparer une promotion (rentrée, fêtes, ouverture).",
 "Prépare un plan de 10 jours avant <b>[événement]</b> pour <b>[activité]</b>.\nDonne 1 publication par jour : teasing, informations, preuve, rappel.\nBudget : très limité (smartphone uniquement). Ton : enthousiaste mais honnête.",
 "Indique des dates réelles et les infos pratiques que tu connais.",
 "J-10 · Teasing : « Un grand changement arrive le 15… »"),
]),
("CARROUSELS", [
("Carrousel éducatif de 7 slides",
 "Expliquer un sujet simplement.",
 "Crée le contenu d'un carrousel de 7 slides sur <b>[sujet]</b> pour <b>[cible]</b>.\nSlide 1 : titre accrocheur. Slides 2 à 6 : un point par slide (15 mots max). Slide 7 : résumé + appel à l'action.\nDonne aussi la légende de la publication.",
 "Utilise Canva ou un autre outil gratuit pour mettre en forme.",
 "Slide 1 : « 5 erreurs dans ton message de prospection »\nSlide 2 : « 1. Commencer par parler de toi »"),
("Carrousel « avant / après »",
 "Montrer une amélioration concrète.",
 "Propose la structure d'un carrousel « avant / après » pour <b>[type de service]</b>.\nDonne : texte de couverture, texte de chaque slide (avant, ce qui change, après), conclusion.\nLe ton doit rester honnête : décris un résultat observable, pas une promesse.",
 "Utilise un exemple réel ou une étude de cas fictive clairement indiquée.",
 "« Avant : annonce de 2 lignes. Après : annonce structurée avec prix, tailles, livraison. »"),
]),
("APPELS À L'ACTION", [
("10 appels à l'action",
 "Dire clairement quoi faire après avoir lu.",
 "Propose 10 appels à l'action pour <b>[type de publication]</b> de <b>[activité]</b>.\nCanaux : WhatsApp, commentaire, message privé.\nVarie : doux, direct, avec question, avec bénéfice.\nChaque appel : 15 mots maximum. Évite la pression abusive.",
 "Un seul appel à l'action par publication : choisis le meilleur.",
 "« Écris-moi “INFO” sur WhatsApp pour recevoir le catalogue. »"),
("Réponse aux commentaires",
 "Transformer les commentaires en conversations.",
 "Voici 5 commentaires reçus : <b>[commentaires]</b>.\nÉcris une réponse courte, polie et utile à chacun. Invite à continuer en message privé quand c'est pertinent. Ne donne pas de prix publics si je ne l'ai pas indiqué.",
 "Réponds toujours avec ton propre ton : relis avant de poster.",
 "« Merci Marie ! Je t'envoie les détails en message privé 😊 »"),
]),
("DESCRIPTIONS DE PRODUITS", [
("Fiche produit complète",
 "Rédiger une description claire et vendeuse.",
 "Rédige une fiche produit pour : <b>[produit]</b>.\nCaractéristiques réelles : <b>[taille, matière, couleurs, prix en FCFA, stock]</b>.\nCible : <b>[cible]</b>. Ton : <b>[ton]</b>.\nStructure : titre, 2 phrases de bénéfices, liste de détails, livraison, appel à l'action.\nN'invente aucune caractéristique : si une information manque, dis-le-moi.",
 "Pour une série de produits, colle plusieurs produits d'un coup.",
 "« Robe wax évasée · Tailles S–XL · 15 000 FCFA\nLégère, confortable, parfaite pour les cérémonies… »"),
("Description courte WhatsApp",
 "Écrire une annonce prête à être partagée en statut ou en groupe.",
 "Transforme ces informations en annonce WhatsApp de 5 lignes maximum avec 2 emojis : <b>[produit, prix, zone, contact]</b>.\nCommence par le bénéfice, termine par comment commander.\nAjoute une variante encore plus courte pour un statut.",
 "Teste deux versions et garde celle qui génère le plus de questions.",
 "« 👟 Baskets confort – 12 000 FCFA. Du 38 au 44, livraison Douala. Écris-moi pour réserver ta paire. »"),
("Descriptions par lot (10 produits)",
 "Gagner du temps sur des catalogues.",
 "Voici la liste de 10 produits avec leurs informations : <b>[liste]</b>.\nÉcris pour chacun une description de 40 à 60 mots dans le même ton, avec les mêmes sections. Garde un style cohérent.\nAjoute à la fin les 3 points à vérifier avant de publier.",
 "Contrôle les prix et caractéristiques ligne par ligne.",
 "Produit 1 : …\nProduit 2 : …\n\nÀ vérifier : tailles, prix, disponibilité."),
]),
("AUTRES PROMPTS DE CONTENU", [
("Réutiliser un contenu en 5 formats",
 "Créer plus avec une seule idée.",
 "À partir de ce texte : <b>[colle ton texte]</b>, crée : 1) un post Facebook, 2) un script TikTok de 30 s, 3) 3 phrases pour un statut WhatsApp, 4) un carrousel de 5 slides, 5) une légende Instagram.\nGarde le même message principal mais adapte le style à chaque canal.",
 "Commence par ton meilleur texte, celui qui a déjà eu de bons retours.",
 "Facebook : …\nTikTok : …\nWhatsApp : …"),
("Adapter le ton à ta cible",
 "Parler comme ton public, sans caricature.",
 "Réécris ce texte pour : <b>[cible, ex. étudiants de 18–25 ans]</b>.\nTexte : <b>[texte]</b>.\nConsignes : français simple, phrases courtes, quelques expressions naturelles mais pas de caricature, pas d'argot excessif. Propose 2 versions : plus formelle / plus décontractée.",
 "Précise les mots que ton public utilise vraiment.",
 "Version décontractée : « Tu veux gagner du temps sur tes devoirs ? Voilà comment… »"),
("Titre et accroche d'article",
 "Trouver un bon titre.",
 "Propose 10 titres pour un article sur <b>[sujet]</b> destiné à <b>[cible]</b>.\nVarie les styles : question, liste, promesse réaliste, erreur à éviter.\nPour les 3 meilleurs, ajoute une phrase d'accroche de 20 mots.",
 "Évite les promesses de résultats garantis.",
 "« 7 erreurs à éviter pour vendre sur WhatsApp »"),
("Idées de contenu éducatif",
 "Montrer ton expertise utile.",
 "Je suis <b>[métier]</b>. Liste 15 sujets éducatifs que mes clients potentiels aimeraient apprendre.\nPour chaque sujet : le problème qu'il résout et le format conseillé (post, vidéo, carrousel).\nPrivilégie les sujets qui montrent mon savoir-faire sans nécessiter de matériel coûteux.",
 "Transforme chaque sujet en série de 3 publications.",
 "Sujet : « Comment bien photographier tes produits avec un téléphone » · Format : vidéo 30 s"),
("Foire aux questions (FAQ)",
 "Répondre d'avance aux questions fréquentes.",
 "Rédige une FAQ de 10 questions pour <b>[activité]</b>.\nInformations officielles : <b>[prix, livraison, paiement (Mobile Money…), délais, politique de retour]</b>.\nRéponses : 2 à 3 phrases, ton aimable. Si une information manque, écris [À COMPLÉTER].",
 "Publie la FAQ en publication épinglée ou en statut WhatsApp Business.",
 "Q : Comment payer ? R : Par Mobile Money ou à la livraison dans Douala…"),
("Idées de contenu viral réaliste",
 "Tester des formats sans promettre de viralité.",
 "Propose 10 formats de vidéos courtes simples à produire avec un téléphone pour <b>[activité]</b> : coulisses, mythe vs réalité, réponse à un commentaire, tutoriel express, etc.\nPour chaque format : à quoi ressemble la vidéo + une accroche d'exemple.\nRappel : personne ne peut garantir la viralité, l'objectif est de tester régulièrement.",
 "Publie 1 format par semaine et garde un tableau des résultats.",
 "Format « Mythe vs réalité » : « Non, tu n'as pas besoin d'un ordinateur pour commencer. »"),
]),
]

def ch4():
    o = chapter(4, "25 PROMPTS POUR CRÉER DU CONTENU", "Des prompts détaillés, prêts à copier-coller. Tu remplaces les [crochets], tu relis, tu publies.")
    o += ('<section>' + callout("Comment utiliser ce chapitre", "<p>Chaque prompt a 4 parties : <strong>Objectif</strong> (à quoi il sert), <strong>Prompt</strong> (à copier), <strong>Comment l'adapter</strong> et un <strong>Exemple de résultat</strong>. Les exemples sont illustratifs : ton résultat sera différent, et c'est normal.</p>", "info", "📘") + '</section>')
    n = 0
    for cat, items in P:
        o += '<section>' + h2(cat)
        for (t, ob, pr, ad, ex) in items:
            n += 1
            o += prompt_box(n, t, pr, ob, ad, ex)
        o += '</section>'
    assert n >= 25, n
    o += ('<section>' + play(["Choisis 3 prompts de ce chapitre qui correspondent à ton activité (ou à celle d'un proche).",
        "Remplace les crochets avec de vraies informations et génère les contenus.",
        "Relis, corrige, ajoute un détail personnel, puis publie ou enregistre le contenu.",
        "Note quel prompt t'a donné le meilleur résultat et pourquoi."]) + '</section>')
    return o
